# ====================================================================
# ANALYTICS ENGINE: GROUPING AND ROI AGGREGATION PER INFLUENCER TIER
# ====================================================================

# Step 1: Calculate total gross revenue and net revenue generated by each custom promo code
df_revenue = df_attribution.groupby('custom_promo_code').agg(
    total_gross_revenue=('order_value', 'sum'),
    total_conversions=('conversion_id', 'count')
).reset_index()

# Step 2: Merge the revenue metrics with the campaign roster to tie it back to costs
df_merged = pd.merge(df_roster, df_revenue, on='custom_promo_code', how='left').fillna(0)

# Step 3: Join with the influencers table to bring the 'tier' classification into context
df_final_reporting = pd.merge(df_merged, df_influencers[['influencer_id', 'tier']], on='influencer_id', how='left')

# Step 4: Aggregate data by Tier to find out which influencer scale delivers the best return
tier_performance = df_final_reporting.groupby('tier').agg(
    total_spend=('contract_cost', 'sum'),
    total_revenue=('total_gross_revenue', 'sum'),
    total_conversions=('total_conversions', 'sum')
).reset_index()

# Step 5: Engineering the core business metrics: Cost Per Acquisition (CPA) and Return on Investment (ROI)
tier_performance['cost_per_acquisition'] = round(tier_performance['total_spend'] / tier_performance['total_conversions'], 2)
tier_performance['net_profit'] = tier_performance['total_revenue'] - tier_performance['total_spend']
tier_performance['roi_percentage'] = round((tier_performance['net_profit'] / tier_performance['total_spend']) * 100, 2)

# Sort performance by the highest ROI percentage
tier_performance = tier_performance.sort_values(by='roi_percentage', ascending=False)

print("=== EXECUTIVE ROI METRICS PER INFLUENCER TIER ===")
print(tier_performance.to_string(index=False))
